support theme runtime change
shoutem/theme pull request #63
Opened 2021-12-22 14:15 UTC by sstimac

- re-render and recalculate style for connected components when the theme changes. Component style is calculated based on few parameters : 

- **Main theme style** ( binding the style to component directly )
- **Style provided by the parent to the children** ( Style calculated based on JSX composition ). This one should be deprecated over time, and therefore simplify the logic here
- **StyleNames** ( prop containing keyed sets of styles defined in theme )
- **Manual style** passed directly to component via `style` prop.

first two bullet points are what changes once we change the theme inside the app, and therefore need to be covered by this PR. How we did it is explained below.

- move parent/child style to props instead of context. previously every connected component acted as new context provider for children, and context consumer of the parent context. Since the children weren't always an immediate node from parent ( style compositions can go more levels in JSX depth, sometimes context change wouldn't propagate the rerender. This is why the children style is now moved to props, to trigger proper lifecycle methods

- Theme subscriptions ( to again, avoid faulty context propagation ). Due to the same issue as above, we had to provide some kind of mechanic that will detect theme context change, anywhere in the tree. Unlike the parent / child style resolution, here the resolved styling comes directly from the theme, requiring a bit different style propagation.

2021-12-23 10:08 UTC, Definitely-Not-Vlad requested changes

2021-12-23 10:08 UTC, Definitely-Not-Vlad commented on src/StyleProvider.js
> +    const { theme } = this.state;
Elsewhere you destructure props first. Can we always do props first then state? Make a convention out of it?
E.g.:
1. Props `const { derp } = this.props;`
2. State `const { herp } = this.state;
3. Arguments `const { lerp } = methodArgument;`

2021-12-23 10:08 UTC, Definitely-Not-Vlad commented on src/connectStyle.js
> +        });
Could you please elaborate on this, I'd love to understand this part.

Why do we apply props only to valid elements and what is an invalid element?

Why do we return invalid elements without props being added?

2021-12-24 08:11 UTC, ltatarev submitted a review, later dismissed

2021-12-24 08:11 UTC, ltatarev commented on src/connectStyle.js
> +        transformProps: PropTypes.func,
Missing some `defaultProps`? 👀

2022-03-31 15:11 UTC, toroz approved these changes

2022-05-05 09:33 UTC, Definitely-Not-Vlad approved these changes

2022-05-05 09:37 UTC, merged